### ISSUE TITLE
Message attachments visual bug

### ISSUE THREAD

**Issue by IKSAPGitHub** [incpi/Dark-CPI-Web-Extension#18]
**Describe the bug**
Hello,

Thank you for the quick fix for my previous issue!

now I noticed a bug in the message attachments, the background remains white and the messages seem to be aligned on top of each other.

**To Reproduce**
1. Go to message processing logs
2. Click on message with any attachment in it
4. See visual bug

**Version**
1.3.2

**Environment**
multi

**Screenshots**
![image](https://github.com/user-attachments/assets/0cf1b7fd-9d6a-404c-a488-d8552d29940f)

**Desktop (please complete the following information):**
 - OS: w11pro 64bit
 - Browser chrome

**Comment by incpi** [comment]
Hello @IKSAPGitHub 

Thank you so much for help me out by your inputs.

I fixed in v1.2 around but something changed in CSS. I fixed it as well.
![image](https://github.com/user-attachments/assets/dc9b1137-6fe7-452d-bd86-efe40c88a735)

Please confirm if this fixes the issue.

**Comment by IKSAPGitHub** [comment]
Hello,

Unfortunately, this problem still exists.

![image](https://github.com/user-attachments/assets/3b40d092-98d3-4759-8f00-ee9789d10d29)

**Comment by incpi** [comment]
Fixed with patch 1.3.4.1 (fixing few cases it doesn't work properly), So closing this.

Thank you so much.
